name: Dev Cont

#
# Creates dev container and runs the init just recipe.
#

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
    paths:
      - .github/workflows/dev-cont.yaml
      - .devcontainer/**
  schedule:
    # At 04:20 on Monday.
    - cron: 20 4 * * 1

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  skip:
    name: Skip
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    outputs:
      skip: ${{ steps.skip.outputs.should_skip }}
    steps:
      - id: skip
        uses: fkirc/skip-duplicate-actions@f75f66ce1886f00957d99748a42c724f4330bdcf # v5.3.1
        with:
          concurrent_skipping: always
          skip_after_successful_duplicate: true

  dev-cont:
    needs: skip
    if: needs.skip.outputs.skip != 'true'
    name: Dev Cont
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0

      - name: Set up dev container CLI
        run: npm install -g @devcontainers/cli

      - name: Get dev container CLI version
        run: devcontainer --version

      - name: Create and run dev container
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: devcontainer up --workspace-folder=.

      - name: Check that token is set in dev container
        run: |
          devcontainer exec \
            --workspace-folder=. \
            /usr/bin/env zsh --interactive --login -c \
              "printenv | grep -G -q ^GITHUB_TOKEN="

      - name: Run init just recipe in dev container
        run: |
          devcontainer exec \
            --workspace-folder=. \
            /usr/bin/env zsh --interactive --login -c \
              "just init"
